trigger:
  branches:
    include:
    - '*'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: build
    pool:
      name: GRC-ELM-CP-Build-Pool
      demands:
      - Agent.Name -equals cp-build
    steps:
    - task: CmdLine@2
#      continueOnError: true
      inputs:
        script: cp /root/.embedmongo/gradlew .
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST/*.*'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
 #   - task: PublishBuildArtifacts@1
 #     inputs:
 #       PathtoPublish: '$(System.DefaultWorkingDirectory)/build/reports/tests/test'
 #       ArtifactName: 'results'
 #       publishLocation: 'Container'
 #       StoreAsTar: true
        