trigger:
  branches:
    include:
    - '*'

variables:
- name: buildStatus
  value: pass'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: build
    pool:
      name: GRC-ELM-CP-Build-Pool
      demands:
      - Agent.Name -equals cp-build
    steps:
    - script: 'cp /root/.embedmongo/gradlew .'
    - script: 'chmod -R 777 /azp/_work/1/s'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean build'
        publishJUnitResults: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build/reports/tests/test'
        ArtifactName: 'results'
        publishLocation: 'Container'
        StoreAsTar: true
        