
package com.datacert.ebilling.digsig.api.trustweaver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Signature switch
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SwitchService", targetNamespace = "http://www.trustweaver.com/tsswitch", wsdlLocation = "https://tseiod.trustweaver.com/ts/svs.asmx?wsdl")
public class SwitchService
    extends Service
{

    private final static URL SWITCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.datacert.ebilling.digsig.api.trustweaver.SwitchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.datacert.ebilling.digsig.api.trustweaver.SwitchService.class.getResource(".");
            url = new URL(baseUrl, "https://tseiod.trustweaver.com/ts/svs.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://tseiod.trustweaver.com/ts/svs.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SWITCHSERVICE_WSDL_LOCATION = url;
    }

    public SwitchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SwitchService() {
        super(SWITCHSERVICE_WSDL_LOCATION, new QName("http://www.trustweaver.com/tsswitch", "SwitchService"));
    }

    /**
     * 
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap() {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap12")
    public SwitchServiceSoap getSwitchServiceSoap12() {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap12"), SwitchServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap12")
    public SwitchServiceSoap getSwitchServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap12"), SwitchServiceSoap.class, features);
    }

}
