
package com.datacert.ebilling.digsig.api.trustweaver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SwitchServiceSoap", targetNamespace = "http://www.trustweaver.com/tsswitch")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SwitchServiceSoap {


    /**
     * 
     * @return
     *     returns com.datacert.ebilling.digsig.api.trustweaver.ServiceInfoResult
     */
    @WebMethod(operationName = "GetServiceInfo", action = "http://www.trustweaver.com/tsswitch#GetServiceInfo")
    @WebResult(name = "GetServiceInfoResult", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "GetServiceInfoResult")
    public ServiceInfoResult getServiceInfo();

    /**
     * 
     * @param request
     * @return
     *     returns com.datacert.ebilling.digsig.api.trustweaver.SignResponse
     */
    @WebMethod(operationName = "Sign", action = "http://www.trustweaver.com/tsswitch#Sign")
    @WebResult(name = "SignResult", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "SignResult")
    public SignResponse sign(
        @WebParam(name = "SignRequest", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "request")
        SignRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.datacert.ebilling.digsig.api.trustweaver.ValidateResponse
     */
    @WebMethod(operationName = "Validate", action = "http://www.trustweaver.com/tsswitch#Validate")
    @WebResult(name = "ValidateResult", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "ValidateResult")
    public ValidateResponse validate(
        @WebParam(name = "ValidateRequest", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "request")
        ValidateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.datacert.ebilling.digsig.api.trustweaver.ValidateArchiveResponse
     */
    @WebMethod(operationName = "ValidateArchive", action = "http://www.trustweaver.com/tsswitch#ValidateArchive")
    @WebResult(name = "ValidateArchiveResult", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "ValidateArchiveResult")
    public ValidateArchiveResponse validateArchive(
        @WebParam(name = "ValidateArchiveRequest", targetNamespace = "http://www.trustweaver.com/tsswitch", partName = "request")
        ValidateArchiveRequest request);

}
