
package com.wkelms.ebilling.digsig.api.trustweaver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Signature switch
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SwitchService", targetNamespace = "http://www.trustweaver.com/tsswitch")
public class SwitchService
    extends Service
{

    private final static URL SWITCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException SWITCHSERVICE_EXCEPTION;
    private final static QName SWITCHSERVICE_QNAME = new QName("http://www.trustweaver.com/tsswitch", "SwitchService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://twod-test.trustweaver.com/ts/svs.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SWITCHSERVICE_WSDL_LOCATION = url;
        SWITCHSERVICE_EXCEPTION = e;
    }

    public SwitchService() {
        super(__getWsdlLocation(), SWITCHSERVICE_QNAME);
    }

    public SwitchService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SWITCHSERVICE_QNAME, features);
    }

    public SwitchService(URL wsdlLocation) {
        super(wsdlLocation, SWITCHSERVICE_QNAME);
    }

    public SwitchService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SWITCHSERVICE_QNAME, features);
    }

    public SwitchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SwitchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap() {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SWITCHSERVICE_EXCEPTION!= null) {
            throw SWITCHSERVICE_EXCEPTION;
        }
        return SWITCHSERVICE_WSDL_LOCATION;
    }

}
