
package com.wkelms.ebilling.digsig.api.trustweaver;

import groovy.util.logging.Log;
import groovy.util.logging.Slf4j;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.support.PropertiesLoaderUtils;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Signature switch
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SwitchService", targetNamespace = "http://www.trustweaver.com/tsswitch", wsdlLocation = "${wsdlUrl}")
public class SwitchService
    extends Service
{
    private final static URL SWITCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException SWITCHSERVICE_EXCEPTION;
    private final static QName SWITCHSERVICE_QNAME = new QName("http://www.trustweaver.com/tsswitch", "SwitchService");

    static {
        Properties properties = new Properties();
        URL wsdlUrl = null;
        WebServiceException e = null;
        try {
            properties = PropertiesLoaderUtils.loadAllProperties("application.yml");
            wsdlUrl = new URL(properties.getProperty("wdslURL").toString());
//            System.out.println(properties.values());
//            System.out.println(properties.getProperty("wdslURL"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch(Exception ex1) {}
        SWITCHSERVICE_WSDL_LOCATION = wsdlUrl;
        SWITCHSERVICE_EXCEPTION = e;
    }

    public SwitchService() {
        super(__getWsdlLocation(), SWITCHSERVICE_QNAME);
    }

    public SwitchService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SWITCHSERVICE_QNAME, features);
    }

    public SwitchService(URL wsdlLocation) {
        super(wsdlLocation, SWITCHSERVICE_QNAME);
    }

    public SwitchService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SWITCHSERVICE_QNAME, features);
    }

    public SwitchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SwitchService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap() {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchServiceSoap
     */
    @WebEndpoint(name = "SwitchServiceSoap")
    public SwitchServiceSoap getSwitchServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.trustweaver.com/tsswitch", "SwitchServiceSoap"), SwitchServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SWITCHSERVICE_EXCEPTION!= null) {
            throw SWITCHSERVICE_EXCEPTION;
        }
        return SWITCHSERVICE_WSDL_LOCATION;
    }

}
